### ISSUE TITLE
LOUD

### ISSUE THREAD

**Issue by julsraemy** [wissen-ist-acht/digitalhistory.intro#4]
First of all, I want to say how much I appreciate that you’ve introduced the concept of Linked Open Usable Data (LOUD) in your course. It’s an important and valuable topic. Having extensively [studied this concept through my PhD research](https://phd.julsraemy.ch/loud), I have a slightly different view regarding the examples given, such as Wikidata, Wikibase, or Geonames.

Based on the definition provided by Rob Sanderson, who originally coined the term, Linked Art, the Web Annotation Data Model, and the IIIF Presentation API 3.0 are standards that are more aligned with the [LOUD design principles](https://linked.art/loud/). These principles go beyond Berners-Lee's 5-star deployment scheme for Open Data.

**Comment by wissen-ist-acht** [comment]
thank you for your comment!
we were already planning to update the contents for the upcoming semester, so thanks for the input.
